apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist2
  namespace: quotaexample
  labels:
    app: tasklist2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklist2
  template:
    metadata:
      labels:
        app: tasklist2
    spec:
      containers:
      - name: tasklist2
        image: despinalr/tasklist
        resources:
          requests:
            cpu: 40m
            memory: 30Mi
          limits:
            cpu: 40m
            memory: 30Mi