apiVersion: v1
kind: Pod
metadata:
  name: tasklist-manualpod2
  namespace: quotaexample
spec:
  containers:
  - name: tasklist
    image: despinalr/tasklist
    resources:
      requests:
        cpu: 60m
        memory: 30Mi
      limits:
        cpu: 60m
        memory: 30Mi