apiVersion: v1
kind: Pod
metadata:
  name: tasklist-manualpod3
  namespace: quotaexample
spec:
  containers:
  - name: tasklist
    image: despinalr/tasklist
    resources:
      requests:
        cpu: 20m
        memory: 10Mi
      limits:
        cpu: 20m
        memory: 10Mi