apiVersion: v1
kind: Service
metadata:
  labels:
    app: tasklist
  name: tasklist-service
  namespace: quotaexample
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tasklist
  type: NodePort
