apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: default
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/despinalr/tasklist
    branch: master
    period: 60s
    dir: k8s
    auth: none